language: csharp

dotnet: 2.1.508 #lts
mono: 5.20.1

matrix:
  include:
    - os: osx
      osx_image: xcode9   
    - os: linux
      dist: trusty
      sudo: required



install:
  - msbuild /t:restore

script:
  - msbuild /p:Configuration=Release

branches:
  only:
    - master